[project]
name = "ds-artificial-neural-networks"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "setuptools<81",
    "tensorboard>=2.20.0",
    "tensorflow>=2.21.0",
    "tensorflow-docs>=2025.2.19.33219",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
